### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Stoya13** [schadis/DMWC-Warrior#1]
Hi, what level toon is this recommended for as im getting this error on a low level toon (lv10)

Message: Interface\AddOns\DMWC-Warrior\Rotation.lua:1385: attempt to call method 'CustomTarget' (a nil value)

**Comment by schadis** [comment]
lvl 60 raid with 2 onehanders or a 2hander furry spec

**Comment by Stoya13** [comment]
thank you.
